export const INITIALIZE_CATALOG = "INITIALIZE_CATALOG";
export const PRODUCT_DETAILS = "PRODUCT_DETAILS";
export const ADD_TO_COMPARE = "ADD_TO_COMPARE";
export const REMOVE_FROM_COMPARE = "REMOVE_FROM_COMPARE";